"""Download the third-party assets listed in assets/asset_manifest.json.

    python tools/fetch_assets.py            # fetch missing files
    python tools/fetch_assets.py --force    # re-download everything

Textures land in assets/textures/<key>/{albedo,normal,rough}.jpg and skies in
assets/environments/sky/<key>.hdr. All sources are CC0 (Poly Haven); credits
are written to assets/CREDITS.md.
"""
import json
import pathlib
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets" / "asset_manifest.json"
API = "https://api.polyhaven.com/files/"
MAPS = {"albedo": "Diffuse", "normal": "nor_gl", "rough": "Rough"}


def get_json(url):
    req = urllib.request.Request(url, headers={"User-Agent": "CaLon-asset-fetch/1.0"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def download(url, dest, force):
    if dest.exists() and not force:
        return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": "CaLon-asset-fetch/1.0"})
    with urllib.request.urlopen(req, timeout=120) as r:
        dest.write_bytes(r.read())
    return True


def main():
    force = "--force" in sys.argv
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    credits = []
    for key, spec in manifest["textures"].items():
        files = get_json(API + spec["source"])
        for name, map_key in MAPS.items():
            url = files[map_key]["1k"]["jpg"]["url"]
            dest = ROOT / "assets" / "textures" / key / f"{name}.jpg"
            if download(url, dest, force):
                print("fetched", dest.relative_to(ROOT))
        credits.append(f"| `textures/{key}` | [{spec['source']}](https://polyhaven.com/a/{spec['source']}) | CC0 |")
    for key, spec in manifest["hdris"].items():
        files = get_json(API + spec["source"])
        url = files["hdri"][spec.get("resolution", "2k")]["hdr"]["url"]
        dest = ROOT / "assets" / "environments" / "sky" / f"{key}.hdr"
        if download(url, dest, force):
            print("fetched", dest.relative_to(ROOT))
        credits.append(f"| `environments/sky/{key}.hdr` | [{spec['source']}](https://polyhaven.com/a/{spec['source']}) | CC0 |")
    (ROOT / "assets" / "CREDITS.md").write_text(
        "# Asset credits\n\nGenerated by `tools/fetch_assets.py` from `assets/asset_manifest.json`.\n\n"
        "| Asset | Source (Poly Haven) | License |\n|---|---|---|\n" + "\n".join(credits) + "\n",
        encoding="utf-8",
    )
    print("done")


if __name__ == "__main__":
    main()
